<?php
/**
 * Created by PhpStorm.
 * User: baoxulong
 * Date: 2018/6/4
 * Time: 上午11:13
 */

namespace App\Lib;


use App\Interfaces\RabbitMQInterface;

class Producer extends RabbitMQ implements RabbitMQInterface
{
    protected static $instance;
    protected static $route_key;
    protected $i = 0;

    public static function init($config)
    {
        parent::init($config); // TODO: Change the autogenerated stub
        if (empty(self::$instance)) {
            self::$instance = new self();
        }
        return self::$instance;
    }

    /**
     * @param $exchange_name
     * @return $this|mixed
     * @throws \AMQPConnectionException
     * @throws \AMQPExchangeException
     */
    public function setExchange($exchange_name)
    {
        // TODO: Implement setExchange() method.
        self::$amqpExchange = new \AMQPExchange(self::$amqpChannel);
        self::$amqpExchange->setName($exchange_name);
        return $this;
    }

    public function bind($route_key)
    {
        self::$route_key = $route_key;
        return $this;
    }

    /**
     * @param String $message
     * @return mixed|void
     */
    public function exec(String $message ='')
    {
//        var_dump($this->i);
        $this->i++;
        // TODO: Implement exec() method.
        echo "Send Message:" . self::$amqpExchange->publish($message, self::$route_key) . PHP_EOL;
    }


}